sensibilizaInsert: false
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://www.db4free.net:3306/tcdnetflix?noAccessToProcedureBodies=true
        username: tcduser
        password: tcdnetf20
        driverClassName: com.mysql.cj.jdbc.Driver